### ISSUE TITLE
Error when trying to check logs

### ISSUE THREAD

**Issue by SmirnovStepan** [my8100/scrapydweb#155]
## 500 (INTERNAL SERVER ERROR): 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
- **Request URL:** http://151.248.121.203:5000/1/log/stats/sds/fishersci_search/2020-07-13T15_50_02/
- **Traceback:**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/scrapydweb/views/files/log.py", line 150, in dispatch_request
    self.stats = parse(self.text)
  File "/usr/local/lib/python3.6/dist-packages/logparser/scrapylogparser.py", line 25, in parse
    return ScrapyLogParser(text, headlines, taillines).main()
  File "/usr/local/lib/python3.6/dist-packages/logparser/scrapylogparser.py", line 32, in __init__
    text = text.strip()
MemoryError

```
- **OS:** Linux-4.15.0-109-generic-x86_64-with-Ubuntu-18.04-bionic
- **Python:** 3.6.9
- **ScrapydWeb:** 1.4.0
- **LogParser:** 0.8.2
- **Scrapyd servers amount:** 1
- **User-Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
- **Request Method:** GET
- **Request Args:** ImmutableMultiDict([])
- **Form Data:** ImmutableMultiDict([])
- **Files Data:** ImmutableMultiDict([])
- **Request Referer:** http://151.248.121.203:5000/1/jobs/

**Comment by SmirnovStepan** [comment]
I've written the log to a .txt file - it's around 120 mb

**Comment by my8100** [comment]
You should run logparser at the same time.
