### ISSUE TITLE
Passing arguments to scraper

### ISSUE THREAD

**Issue by ohenrik** [my8100/scrapydweb#19]
Is it possible to pass arguments to the scraper?

When i start my scraper through the command line i add `-s symbol=APPL` to the scraper.
so for example: `scrapy crawl my_scaper -a symbol=APPL`

I tried adding this to the `additional` text box, however it does not seem to be added to the command.

**Comment by my8100** [comment]
It should work if you add '-d symbol=APPL' in the additional text box!

**Comment by ohenrik** [comment]
Thank you, this worked :tada:

**Comment by echoocking** [comment]
i want pass params to spider , so i use __init__ func to get -a params like this

```
    def __init__(self, mgo_db, mgo_table):
        mgo_conn = get_mgo_client()
        self.mgo_table = mgo_conn[mgo_db][mgo_table]
        super(MtopSpider, self).__init__()

```
and add
 '-d mgo_db=mtop 
 -d mgo_table=taolijin'
in the additional text box

but i got 

```
2019-03-20 21:33:09 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/scrapyd-server-b9lo-2yl/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/root/.local/share/virtualenvs/scrapyd-server-b9lo-2yl/lib/python3.7/site-packages/scrapy/crawler.py", line 79, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/root/.local/share/virtualenvs/scrapyd-server-b9lo-2yl/lib/python3.7/site-packages/scrapy/crawler.py", line 102, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/root/.local/share/virtualenvs/scrapyd-server-b9lo-2yl/lib/python3.7/site-packages/scrapy_redis/spiders.py", line 153, in from_crawler
    obj = super(RedisSpider, self).from_crawler(crawler, *args, **kwargs)
  File "/root/.local/share/virtualenvs/scrapyd-server-b9lo-2yl/lib/python3.7/site-packages/scrapy/spiders/__init__.py", line 51, in from_crawler
    spider = cls(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_version'
```

what shoud i do for this? thanks a lot :)

**Comment by my8100** [comment]
![image](https://user-images.githubusercontent.com/37427675/54688753-354e3080-4b59-11e9-815a-5509091657f3.png)

**Comment by echoocking** [comment]
schedule.json is correct. 
__init__ func need change to
