### ISSUE TITLE
Http 400 when trying to access

### ISSUE THREAD

**Issue by rpinheiro-home** [my8100/scrapydweb#200]
I followed the initial guide step by step and when trying to access the initial URL I get an http code 400 and in the log only a json appears containing: node:1

What am I missing?

It's more a question than an issue
Thanks

**Comment by rpinheiro-home** [comment]
![image](https://user-images.githubusercontent.com/84727756/162975673-3e933355-3ece-4384-9e6f-29eb0cd4fd22.png)

**Comment by rpinheiro-home** [comment]
```
[2022-04-12 10:40:48,667] DEBUG    in IndexView: view_args of http://XXX.XXX.XXX.XXX:5000/
{
    "node": 1
}
[2022-04-12 10:40:48,668] INFO     in werkzeug: XXX.XXX.XXX.XXX- - [12/Apr/2022 10:40:48] "GET / HTTP/1.1" 400 -

```

**Comment by rpinheiro-home** [comment]
I don't know exactly why (because I don`t know flask) but commented this lines and now I can acess.

```
        # if app.testing:
        # self.logger.debug('view_args of %s\n%s', request.url, self.json_dumps(request.view_args))
        # if request.args:
        #     self.logger.debug('request.args of %s\n%s', request.url, self.json_dumps(request.args))
        # if request.form:
        #     self.logger.debug('request.form from %s\n%s', request.url, self.json_dumps(request.form))
        # if request.json:
        #     self.logger.debug('request.json from %s\n%s', request.url, self.json_dumps(request.json))
        # if request.files:
        #     self.logger.debug('request.files from %s\n\n    %s\n', request.url, request.files)
```

**Comment by Pandaaaa906** [comment]
it's seem that werkzeug 2.1.0 got some break change about request.json
you can just specific werkzeug version to 2.0.3 will sovle the case
https://github.com/pallets/werkzeug/issues/2339

**Comment by cced3000** [comment]
thanks @Pandaaaa906  ，I solved the problem through your suggestion，pip install Werkzeug==2.0.3

**Comment by espoirMur** [comment]
> thanks @Pandaaaa906 ，I solved the problem through your suggestion，pip install Werkzeug==2.0.3


Thanks you..

**Comment by Ngounse** [comment]
please help

**Comment by casual-silva** [comment]
> Http 400 when trying to access i got the same problem [ ![Screenshot from 2022-05-10 16-21-12](https://user-images.githubusercontent.com/73209949/167595580-798e1ce5-a719-4102-8cc3-e6033b4ce52b.png) ](URL)
> 
> and this what in terminal I get `[2022-05-10 16:23:21,104] INFO in werkzeug: * Running on all addresses (0.0.0.0) WARNING: This is a development server. Do not use it in a production deployment.
> 
> * Running on http://xxx.xxx.x.x:5000
> * Running on http://xxx.xxx.x.x:5000 (Press CTRL+C to quit)
>   [2022-05-10 16:23:24,577] INFO     in werkzeug: 127.0.0.1 - - [10/May/2022 16:23:24] "GET / HTTP/1.1" 400 -`

>> Bad Request
The browser (or proxy) sent a request that this server could not understand.

我也遇到了同样的问题 我的机器是ubuntu18.04  
但是在本地windows  是正常加载的  不知道什么原因

I ran into the same problem with ubuntu18.04
But Windows loads normally locally  for unknown reason

**Comment by Ngounse** [comment]
> > Http 400 when trying to access i got the same problem [ ![Screenshot from 2022-05-10 16-21-12](https://user-images.githubusercontent.com/73209949/167595580-798e1ce5-a719-4102-8cc3-e6033b4ce52b.png) ](URL)
> > and this what in terminal I get `[2022-05-10 16:23:21,104] INFO in werkzeug: * Running on all addresses (0.0.0.0) WARNING: This is a development server. Do not use it in a production deployment.
> > 
> > * Running on http://xxx.xxx.x.x:5000
> > * Running on http://xxx.xxx.x.x:5000 (Press CTRL+C to quit)
> >   [2022-05-10 16:23:24,577] INFO     in werkzeug: 127.0.0.1 - - [10/May/2022 16:23:24] "GET / HTTP/1.1" 400 -`
> 
> > > Bad Request
> > > The browser (or proxy) sent a request that this server could not understand.
> 
> 我也遇到了同样的问题 我的机器是ubuntu18.04 但是在本地windows 是正常加载的 不知道什么原因
> 
> I ran into the same problem with ubuntu18.04 But Windows loads normally locally for unknown reason
Thank you your help 

i'm running on zorin os 16 ( ubuntu 20.0.4 base) 
i been try to fix it but get no where

**Comment by casual-silva** [comment]
>I solved the problem to locate the source code and found it was caused by the Werkzeug version problem
As he said, @pandaaaa906 can be solved by lowering Werkzeug

Reinstall >> pip install Werkzeug==2.0.2

**Comment by Ngounse** [comment]
> > I solved the problem to locate the source code and found it was caused by the Werkzeug version problem
> > As he said, @Pandaaaa906 can be solved by lowering Werkzeug
> 
> Reinstall >> pip install Werkzeug==2.0.2

it's work now @casual-silva  thank you a lot

**Comment by Nirav-Ironlist** [comment]
I also Solve same problem by your suggestion.Thank You

> thanks @Pandaaaa906 ，I solved the problem through your suggestion，pip install Werkzeug==2.0.3

**Comment by minikiller** [comment]
I pip install Werkzeug==2.0.3,but got following error:

```
Traceback (most recent call last):
  File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/bin/scrapydweb", line 5, in <module>
    from scrapydweb.run import main
  File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/scrapydweb/__init__.py", line 9, in <module>
    from flask import Flask, current_app, render_template, url_for
  File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'
```

**Comment by Ngounse** [comment]
> venv

I saw it complain from flask maybe that the problem here my flask --v Flask==2.1.2

**Comment by Ngounse** [comment]
can i also see you 
pip freeze

**Comment by Resalee** [comment]
> I pip install Werkzeug==2.0.3,but got following error:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/bin/scrapydweb", line 5, in <module>
>     from scrapydweb.run import main
>   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/scrapydweb/__init__.py", line 9, in <module>
>     from flask import Flask, current_app, render_template, url_for
>   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/flask/__init__.py", line 4, in <module>
>     from . import json as json
>   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 8, in <module>
>     from ..globals import current_app
>   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/flask/globals.py", line 56, in <module>
>     app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
> TypeError: __init__() got an unexpected keyword argument 'unbound_message'
> ```

I have the same problem, did you find out how to fix it?

**Comment by Resalee** [comment]
@minikiller I tried to use docker images from dockerhub, and it worked, this one => https://hub.docker.com/r/ryanvin/scrapydweb

**Comment by afc3liuyuan** [comment]
> > I pip install Werkzeug==2.0.3,but got following error:
> > ```
> > Traceback (most recent call last):
> >   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/bin/scrapydweb", line 5, in <module>
> >     from scrapydweb.run import main
> >   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/scrapydweb/__init__.py", line 9, in <module>
> >     from flask import Flask, current_app, render_template, url_for
> >   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/flask/__init__.py", line 4, in <module>
> >     from . import json as json
> >   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 8, in <module>
> >     from ..globals import current_app
> >   File "/Users/sunlingfeng/guolu/study-scrapy/bookscraper/.venv/lib/python3.8/site-packages/flask/globals.py", line 56, in <module>
> >     app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
> > TypeError: __init__() got an unexpected keyword argument 'unbound_message'
> > ```
> 
> I have the same problem, did you find out how to fix it?

please see: https://github.com/my8100/scrapydweb/issues/202
you can set the flask version to 2.0.2 and Werkzeug version to 2.0.2 by reinstalling.

**Comment by afc3liuyuan** [comment]
Thanks @PandyYang
please see: https://github.com/my8100/scrapydweb/issues/202

reinstall the flask version to 2.0.2 and Werkzeug version to 2.0.2 can resolve this problem.
