### ISSUE TITLE
[PY2] UnicodeDecodeError raised when there are some files with illegal filenames in `SCRAPY_PROJECTS_DIR` 

### ISSUE THREAD

**Issue by chushiyan** [my8100/scrapydweb#48]
Request URL | 
-- | --
'ascii' codec can't decode byte 0xe2 in position 15: ordinal not in range(128)
Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2311, in wsgi_app     response = self.full_dispatch_request()   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1834, in full_dispatch_request     rv = self.handle_user_exception(e)   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1737, in handle_user_exception     reraise(exc_type, exc_value, tb)   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1832, in full_dispatch_request     rv = self.dispatch_request()   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1818, in dispatch_request     return self.view_functions[rule.endpoint](**req.view_args)   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 88, in view     return self.dispatch_request(*args, **kwargs)   File "/usr/local/lib/python2.7/dist-packages/scrapydweb/operations/deploy.py", line 56, in dispatch_request     self.get_modification_times()   File "/usr/local/lib/python2.7/dist-packages/scrapydweb/operations/deploy.py", line 75, in get_modification_times     timestamps = [self.get_modification_time(i) for i in self.project_paths]   File "/usr/local/lib/python2.7/dist-packages/scrapydweb/operations/deploy.py", line 90, in get_modification_time     for dirpath, dirnames, filenames in os.walk(path):   File "/usr/lib/python2.7/os.py", line 296, in walk     for x in walk(new_path, topdown, onerror, followlinks):   File "/usr/lib/python2.7/os.py", line 296, in walk     for x in walk(new_path, topdown, onerror, followlinks):   File "/usr/lib/python2.7/os.py", line 286, in walk     if isdir(join(top, name)):   File "/usr/lib/python2.7/posixpath.py", line 73, in join     path += '/' + b UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 15: ordinal not in range(128)
Linux-4.4.0-117-generic-x86_64-with-Ubuntu-16.04-xenial
2.7.12
1.2.0
0.8.1
2
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
GET
ImmutableMultiDict([])
ImmutableMultiDict([])
ImmutableMultiDict([])

**Comment by my8100** [comment]
It seems that there are some files with illegal filenames in `SCRAPY_PROJECTS_DIR`.
You can change it to another directory before the issue is fixed, or use Python 3.x instead.

**Comment by chushiyan** [comment]
> 
> 
> It seems that there are some files with illegal filenames in `SCRAPY_PROJECTS_DIR`.
> You can change it to another directory before the issue is fixed, or use Python 3.x instead.

It works,thx.

**Comment by my8100** [comment]
@chushiyan, Could you help to test the fix of this issue following these steps?
1. Use the previous setting of `SCRAPY_PROJECTS_DIR`
and ensure that the problem could be reproduced in Python 2.7
2. Press **Ctrl+c** to stop scrapydweb
3. Run `pip uninstall scrapydweb` and then get it reinstalled via git:
 `pip install -U git+https://github.com/my8100/scrapydweb.git`
4. Run `scrapydweb`
5. Visit the *deploy project* page to check if the page could be loaded,
and there are some messages about illegal filenames.

**Comment by chushiyan** [comment]
Sorry, I just saw the message today.  I've completed that project and delivered it to the client. I can't log on to that machine anymore.So , I installed scrapydweb  on another machine that had never had scrapydweb installed . and there are some files  whose filename contain Chinese characters in the scrapy project. I performed the same operations just like that project. It  did not report the same error when visiting the deploy project.

**Comment by my8100** [comment]
Actually, filenames with Chinese are legal. 
Thank you all the same.

**Comment by chushiyan** [comment]
I remember that my project has a file that contains Chinese characters. Upload to that machine, the file name appears garbled.

**Comment by my8100** [comment]
> I remember that my project has a file that contains Chinese characters. Upload to that machine, the file name appears garbled.

That might be the cause.

**Comment by chushiyan** [comment]
This time, I uploaded  that project on the new machine, the filename also appears garbled. But there was no error when visiting deploy project.

**Comment by my8100** [comment]
Is there any message about illegal filenames shown in the page?

**Comment by chushiyan** [comment]
I didn't see any message  about illegal filenames.

**Comment by my8100** [comment]
Are you using scrapydweb from git in Python 2.7?

**Comment by chushiyan** [comment]
I installed scrapydweb via pip ,just like the last time . and in python2.7

**Comment by my8100** [comment]
If so, the problem still cannot be reproduced in the new environment.

**Comment by chushiyan** [comment]
I mean, I use "pip install scrapydweb" .

**Comment by my8100** [comment]
I know what you said.
scrapydweb from git has fixed the problem, 
whereas the pip version is not updated yet.

**Comment by my8100** [comment]
I manage to reproduce the problem with the help of PuTTY,
and the problem is fixed in the latest commit.
