### ISSUE TITLE
timer task does not work

### ISSUE THREAD

**Issue by monstersama** [my8100/scrapydweb#49]
- i cant add timer task and get a error:__init__() got an unexpected keyword argument 'jitter'

Detail:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\py36\lib\site-packages\scrapydweb\operations\schedule.py", line 479, in add_update_task
    replace_existing=True, **self.task_data)
  File "c:\programdata\anaconda3\envs\py36\lib\site-packages\apscheduler\schedulers\base.py", line 411, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "c:\programdata\anaconda3\envs\py36\lib\site-packages\apscheduler\schedulers\base.py", line 905, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "c:\programdata\anaconda3\envs\py36\lib\site-packages\apscheduler\schedulers\base.py", line 890, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
TypeError: __init__() got an unexpected keyword argument 'jitter'

```
kwargs for execute_task():
{
    "task_id": 1
}

task_data for scheduler.add_job():
{
    "coalesce": true,
    "day": "*",
    "day_of_week": "*",
    "end_date": null,
    "hour": "*",
    "id": "1",
    "jitter": 0,
    "max_instances": 1,
    "minute": "*/10",
    "misfire_grace_time": 600,
    "month": "*",
    "name": "test timeer tasks - edit",
    "second": "0",
    "start_date": null,
    "timezone": "Asia/Shanghai",
    "trigger": "cron",
    "week": "*",
    "year": "*"
}
```

**Comment by my8100** [comment]
See https://github.com/my8100/scrapydweb/issues/43#issuecomment-495572025
