### ISSUE TITLE
How to add a timer task to run every hour between 7-12

### ISSUE THREAD

**Issue by JQ-K** [my8100/scrapydweb#57]
如题

**Comment by my8100** [comment]
hour: 7-12
minute: 0
second: 0
Leave the rest as default.

**Comment by JQ-K** [comment]
这样是不是每个整点都会产生一个job， 如果想就一直运行一个job需要怎么操作，thx

**Comment by my8100** [comment]
If you want to automatically start a job at 7 o'clock and get it stopped 5 hours later,
you can pass the `CLOSESPIDER_TIMEOUT` setting ([docs](https://docs.scrapy.org/en/latest/topics/extensions.html#std:setting-CLOSESPIDER_TIMEOUT)).
Besides, `CLOSESPIDER_PAGECOUNT` and `CLOSESPIDER_ITEMCOUNT` may also be useful for you.

```
CLOSESPIDER_TIMEOUT
Default: 0

An integer which specifies a number of seconds.
If the spider remains open for more than that number of second,
it will be automatically closed with the reason closespider_timeout.
If zero (or non set), spiders won’t be closed by timeout.
```

1. Type `-d setting=CLOSESPIDER_TIMEOUT=18000` in the *additional* textarea.

![image](https://user-images.githubusercontent.com/37427675/60233350-8a28e200-98d2-11e9-8bd5-b240c83f47c4.png)

2. Add a timer task.
```
hour: 7
minute: 0
second: 0
# Leave the rest as default.
```

**Comment by JQ-K** [comment]
awesome thanks very much！

**Comment by JQ-K** [comment]
不好意思，运行会报以下错误：
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/usr/local/lib/python3.6/site-packages/scrapy/core/downloader/__init__.py", line 124, in _enqueue_request
    key, slot = self._get_slot(request, spider)
  File "/usr/local/lib/python3.6/site-packages/scrapy/core/downloader/__init__.py", line 108, in _get_slot
    conc, delay = _get_concurrency_delay(conc, spider, self.settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/core/downloader/__init__.py", line 62, in _get_concurrency_delay
    delay = settings.getfloat('DOWNLOAD_DELAY')
  File "/usr/local/lib/python3.6/site-packages/scrapy/settings/__init__.py", line 159, in getfloat
    return float(self.get(name, default))
ValueError: could not convert string to float: '-d setting=CLOSESPIDER_TIMEOUT=3600 in the additional textarea'

**Comment by my8100** [comment]
1. Type the string below in the *additional* textarea:

`-d setting=CLOSESPIDER_TIMEOUT=18000`
